### ISSUE TITLE
TeamRepoHandler errors

### ISSUE THREAD

**Issue by bsundsrud** [XAMPPRocky/octocrab#103]
Hi, I'm trying to use this to do bulk permission updates in our org, and ran into a couple issues (and possible solutions).

In `src/api/teams/team_repos.rs`, both `check_manages` and `add_or_update` try to request a relative URL directly via reqwest, which fails with the error `Error: Http { source: reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }`.  I have a local fork and found that calling `self.crab.absolute_url(&url)?` fixes the issue.  I see there's also a way to call `Octocrab::get` or `Octocrab::put` which handles relative API URLs, but I couldn't find the best way to make the types line up.

I also found an issue with the `add_or_update` body payload.  It serializes a `params::teams::Permission` directly into the body, resulting in the body having just the string of the desired permission, (such as `"admin"`), but the API requires it be in the form `{"permission": "admin"}`.  I fixed this with a private one-field struct:
```
#[derive(Debug, serde::Serialize)]
struct PermissionUpdateBody {
    permission: params::teams::Permission,
}
```

I can open a PR with these fixes if you'd like, I'd just like some guidance on which way to take the relative URL fix (calling `Octocrab::absolute_url` or `Octocrab::get/put`) and where to put the permission update type.

**Comment by bsundsrud** [comment]
There's also some weirdness with how `check_manages` interacts with the GitHub API.  If you have no permissions, you get a 404, which Octocrab will turn into a Json error as it assumes it will be getting back a `models::Repository`.  Maybe the return type should be `Result<Option<Repository>>`? That way you could differentiate between "Has permissions, here's the repo metadata" (`Ok(Some(...))`), "No permissions/repo doesn't exist" (`Ok(None)`), and "There was an error" (`Err(...)`).

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Pull requests are always welcome. These changes all seem sensible to me.

**Comment by bsundsrud** [comment]
I'll put together a PR later this week/weekend then. The only other thing I ran across was making the fields public in models::teams::Permissions so that I could check existing team permissions.

**Comment by bsundsrud** [comment]
Opened as #106.
