### ISSUE TITLE
Update releases

### ISSUE THREAD

**Issue by crqra** [XAMPPRocky/octocrab#115]
Any plans to support the [update releases](https://docs.github.com/en/rest/reference/repos#update-a-release) endpoint?

P.S.: Thanks for this library, really nice!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I have no immediate need for this myself, but contributions are always welcome so if someone wants to make a PR adding it, I'd be happy to include it.

**Comment by crqra** [comment]
I'm fairly new to Rust but I'll have a look at the source code, see if I can get my way around it and open a PR. Thanks!
