### ISSUE TITLE
Update release records

### ISSUE THREAD

**Issue by ctron** [XAMPPRocky/octocrab#130]
I just stumbled over this project when looking for a Rust client for GitHub APIs. And I really liked what I saw.

What bothered me though, was that the project seemed to be kind of dead:

![image](https://user-images.githubusercontent.com/202474/138421282-705a45c5-0e2f-41da-b972-bee0935b3032.png)

Checking the tags, I quickly figured out, that this is just a lack up updated release records.

I would suggest to:

* Either ditch using releases (you can hide the box)
* Or update them with every tag/publish

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've chosen to just hide that.
