### ISSUE TITLE
Serializing `EventType::UnknownEvent` creates an unserializable payload

### ISSUE THREAD

**Issue by ecton** [XAMPPRocky/octocrab#141]
I'm trying to save `octocrab::models::events::Event`s to a local database, and I've run into an issue when trying to restore the Json I've serialized using serde_json.

A problem example event payload looks like this (the watcher's details have been anonymized):

```json
{
    "id": "18645316253",
    "type": {
        "UnknownEvent": "WatchEvent"
    },
    "actor": {
        "id": 000,
        "login": "...",
        "display_login": "...",
        "gravatar_id": "",
        "url": "https://api.github.com/users/...",
        "avatar_url": "https://avatars.githubusercontent.com/u/...?"
    },
    "repo": {
        "id": 247378701,
        "name": "khonsulabs/kludgine",
        "url": "https://api.github.com/repos/khonsulabs/kludgine"
    },
    "public": true,
    "created_at": "2021-10-28T16:52:23Z",
    "payload": {
        "action": "started"
    },
    "org": {
        "id": 50191483,
        "login": "khonsulabs",
        "gravatar_id": "",
        "url": "https://api.github.com/orgs/khonsulabs",
        "avatar_url": "https://avatars.githubusercontent.com/u/50191483?"
    }
}
```

The error I get from the deserialization call is `invalid type: map, expected a string at line 1 column 27`. I recognize that this library isn't designed for this purpose, and I'm skipping these events so this doesn't actually impact my project anymore.

**Comment by wayofthepie** [comment]
Ah, this is a bug. The type for the unknown event should just serialize as the type we get from github. Not as the object it's getting serialized as now. I can look at fixing this over the week.
