### ISSUE TITLE
Examples using `create_jwt` with `from_rsa_pem` are no longer valid.

### ISSUE THREAD

**Issue by Xithrius** [XAMPPRocky/octocrab#156]
Examples such as [`github_app_authentication`](https://github.com/XAMPPRocky/octocrab/blob/master/examples/github_app_authentication.rs) and [`github_app_authentication_manual`](https://github.com/XAMPPRocky/octocrab/blob/master/examples/github_app_authentication_manual.rs) are no longer valid.

Here is an example of [`EncodingKey`](https://github.com/Keats/jsonwebtoken/blob/master/src/encoding.rs#L10-L16) not being able to be passed into [`octocrab::auth::create_jwt`](https://github.com/XAMPPRocky/octocrab/blob/master/src/auth.rs#L36-L61) while using [`EncodingKey.from_rsa_pem`](https://github.com/Keats/jsonwebtoken/blob/master/src/encoding.rs#L30-L42).

```rust
let pem = std::fs::read_to_string(&config.private_key_path).expect("Something went wrong reading the file");

let key = jsonwebtoken::EncodingKey::from_rsa_pem(pem.as_bytes()).unwrap();

let jwt = octocrab::auth::create_jwt(AppId(config.application_id), key);
```

An error like the following is caused, given the above context: 
```rust
error[E0277]: the trait bound `EncodingKey: AsRef<[u8]>` is not satisfied
  --> src/main.rs:46:80
   |
46 |             let jwt = octocrab::auth::create_jwt(AppId(config.application_id), key).unwrap();
   |                                                                                ^^^ the trait `AsRef<[u8]>` is not implemented for `EncodingKey`
   |
note: required by a bound in `create_jwt`
  --> /home/xithrius/.cargo/registry/src/github.com-1ecc6299db9ec823/octocrab-0.13.0/src/auth.rs:22:22
   |
22 | pub fn create_jwt<A: AsRef<[u8]>>(
   |                      ^^^^^^^^^^^ required by this bound in `create_jwt`
```

**Comment by Xithrius** [comment]
I've realized that the problem is the [github source](https://github.com/XAMPPRocky/octocrab/blob/master/src/auth.rs#L36-L61) and [docs.rs](https://docs.rs/octocrab/0.13.0/src/octocrab/auth.rs.html#22-46) being different for sources of the function.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've now published a new version, which should remove this confusion.

**Comment by Xithrius** [comment]
@XAMPPRocky Thank you so much for the quick reply!

The new release works perfectly. Have a good one!

:heart:
