### ISSUE TITLE
Missing request for list for authenticated user

### ISSUE THREAD

**Issue by kafji** [XAMPPRocky/octocrab#182]
Hi, I want to add api request for https://octokit.github.io/rest.js/v18#repos-list-for-authenticated-user but I'm not sure where the it should be located.

Following the octokit api it should be under RepositoryHandler, but it takes owner & repo name as its arguments.

Should I add it under `current` (`octocrab.current().list_for_authenticated_user()`)?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Current seems like the best place for it. Maybe #181 should also be under current for consistency?
