### ISSUE TITLE
Extra %7B in upload URL

### ISSUE THREAD

**Issue by ShouvikGhosh2048** [XAMPPRocky/octocrab#196]
```
#[tokio::main]
async fn main() {
    let release = octocrab::instance()
    .repos("rust-lang", "rust")
    .releases()
    .get_by_tag("1.59.0")
    .await
    .unwrap();
    println!("{:?}",release.upload_url);
}
```

The above code prints:
Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("uploads.github.com")), port: None, path: "/repos/rust-lang/rust/releases/60393040/assets%7B", query: Some("name,label}"), fragment: None }

The url path has an extra %7B at the end. Referring to [this](https://stackoverflow.com/questions/22510329/what-do-the-chars-7d-mean-in-an-url-query) and [this](https://www.geeksforgeeks.org/html-url-encoding/), this is an extra { in the url.

Referring to one [example](https://docs.github.com/en/rest/reference/releases#list-releases) from Github API docs, the Github API returns a URL of the form "https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name,label}", and I guess the part after ? is being treated as a query.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've push up a fix for it, want to give it a shot and I can release a patch release?

**Comment by ShouvikGhosh2048** [comment]
Thanks for quick fix.
Would it be better to remove the {?name,label} part and convert the download_url to a url? Since people will have to remove the {?name,label} if they want to use the url? (Although it is different from what the Github API uses, so it may not be a good idea.)

**Comment by XAMPPRocky** [comment]
I think ideally there would be a `UrlTemplate` type that correctly accepted those parameters and allowed you to generate URLs based on the parameters.
