### ISSUE TITLE
Failure parsing JSON for release listing response

### ISSUE THREAD

**Issue by urma** [XAMPPRocky/octocrab#197]
While trying to fetch the releases for a specific repository (https://github.com/protocolbuffers/protobuf) I am getting the following:
```
thread 'main' panicked at 'Unable to find any acceptable when scraping GitHub: Serde Error: invalid type: null, expected struct User
(...)
Caused by:
    invalid type: null, expected struct User', src/dependencies/libprotobuf.rs:48:10
```

Simplest code that can reproduce the issue is:
```rust
let octocrab = octocrab::instance();

// Returns the first page of all releases.
let mut page = octocrab
    .issues("protocolbuffers", "protobuf")
    .list()
    .send()
    .await?;
```

I have found that making the `author` attribute in https://github.com/XAMPPRocky/octocrab/blob/c78edcd87fa5edcd5a6d0d0878b2a8d020802c40/src/models/repos.rs#L166-L185 as well as making the `uploader` attribute in https://github.com/XAMPPRocky/octocrab/blob/c78edcd87fa5edcd5a6d0d0878b2a8d020802c40/src/models/repos.rs#L189-L203 optional (`Option<crate::models::User>`) the code works as expected.

I have checked the JSON response for the `releases` endpoint for that particular repository (https://api.github.com/repos/protocolbuffers/protobuf/releases) and all the required attributes in both the `author` and `uploader` objects for all `release` instances seem to be properly populated.

**Comment by DrProfSgtMrJ** [comment]
I'm curious if `pub name` should be optional as well. I currently get a similar error when attempting to  get a release that has no name.

**Comment by DrProfSgtMrJ** [comment]
So I got a similar issue 
`Error: Failed to get release JSON Error in assets[0].uploader: missing field `name` at line 1 column 2898.`
 I see that it's not optional at the moment.
 Wondering if I should also override this struct... 
 @urma
