### ISSUE TITLE
Listing pull requests comments response parsing fails for comment of deleted user

### ISSUE THREAD

**Issue by DerMagischeBier** [XAMPPRocky/octocrab#205]
Listing comments from a pull request where there is at least one comment of a deleted user leads to a parsing error for the API response looking like this: `Error("invalid type: null, expected struct User", line: 0, column: 0)`.

Minimal example to reproduce with crate version 0.15.4:
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    octocrab::instance()
        .pulls("cucumber-rs", "cucumber")
        .list_comments(Some(31))
        .send()
        .await?;

    Ok(())
}
```

Looking at the JSON API response of this (https://api.github.com/repos/cucumber-rs/cucumber/pulls/31/comments) one can see the user is set to `null` for some comments. 

Changing the type of `user` from `User` to `Option<User>` in the following code (`models::pulls::Comment`) seems to solve this. Don't know whether it is intended like this.
https://github.com/XAMPPRocky/octocrab/blob/2c382ffdf2e9d0b0da1bf3b5f6565c8683c0de9e/src/models/pulls.rs#L240-L244

This could be related to #197 where there are also some fields set to null but not sure.

**Comment by XAMPPRocky** [comment]
Thank you for your issue!

> Changing the type of user from User to Option<User> in the following code (models::pulls::Comment) seems to solve this. Don't know whether it is intended like this.

That's probably the fix for this, feel to open a PR fixing it, and I can get it in for the next release.
