### ISSUE TITLE
Change `CHANGELOG.md`-Policy

### ISSUE THREAD

**Issue by CommanderStorm** [XAMPPRocky/octocrab#211]
If present GitHub dependabot displays the `CHANGELOG.md` for repos, that have one.
see https://github.com/TUM-Dev/navigatum/pull/94 for an example.

If `CHANGELOG.md` were not present, just the list of commits would be shown see https://github.com/FSTUM/toptool-v3/pull/36

Since `CHANGELOG.md` does not seem relevant in this project anymore (writing release-notes is a pain), it would be nice to remove the old CHANGELOG.

I can write a PR for this if you'd like 😉

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This has been resolved by automating our release process
