### ISSUE TITLE
Github App authentication example fails

### ISSUE THREAD

**Issue by koenw** [XAMPPRocky/octocrab#215]
Hello,

first of all thanks for all your effort resulting in this wonderful library :)

I'm confused as to how to authenticate as a Github App, and I'm unable to reproduce the example.

Steps I took:

* [Register a Github App](https://github.com/settings/apps)
* make a note of the *App Id*
* Generate a private key for it at https://github.com/settings/apps/<bot-name> (bottom of the page)
* From inside the octocrab repo:
  ```sh
    export GITHUB_APP_id=123456
    export GITHUB_APP_PRIVATE_KEY=$(cat <bot-name>.<date>.private-key.pem)
    cargo run --example github_app_authentication
  ```

This will result in a (401, "Bad credentials") response from Github.

Am I misunderstanding something here, or did I run into an issue?

Thank you for your help :)

**Comment by soonum** [comment]
Hi there,

I'm facing the same problem in my implementation using the OctocrabBuilder.
I've looked into the octocrab codebase in `src/auth.rs`. The implementation is straight forward though. Could this be related to a breaking change in Github API that induce authentication failure.

@XAMPPRocky I'm ready to help fixing this if you can tell me where to look.

**Comment by koenw** [comment]
While I haven't delved into the octocrab codebase, I'm not sure this is because of a change in the Github API because the manual example (`github_app_authentication_manual`) *does* work for me.

**Comment by soonum** [comment]
Thanks for pointing that out @koenw, I used the example and it worked like a charm. It was just a misunderstanding from me on how work GitHub App authentication.

**Comment by Kobzol** [comment]
The authentication is correct, but the example is wrong, the API call that it makes has to be authenticated through an installation ID.
