### ISSUE TITLE
Search Pull Requests

### ISSUE THREAD

**Issue by llogiq** [XAMPPRocky/octocrab#22]
The github page allows searching pull requests by organization (see for example the weekly PRs link in [this week in rust](https://this-weel-in-rust.org)).

This allows a more fine grained query (as opposed to getting all queries and filtering them after the fact) and may help conserve bandwidth. It does need an authenticated user, though, as far as I know.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I’ve started work on implementing the search API. I’ll have an initial implementation with the next couple of days for issues and pull requests and then other search endpoints can be added later as needed.

**Comment by XAMPPRocky** [comment]
I've just pushed an initial version of the search API onto master. You can use it like the following.
```rust
let page = octocrab::instance()
    .search()
    .issues_or_pulls("GitHub Octocrab in:readme user:ferris")
    .sort("comments")
    .order("asc")
    .send()
    .await?;
```
