### ISSUE TITLE
Add StarGazers API Support

### ISSUE THREAD

**Issue by lineville** [XAMPPRocky/octocrab#226]
Hi there 👋 I was working on a recent [project](https://github.com/lineville/star-scraper) that utilizes the [GitHub StarGazer API](https://docs.github.com/en/rest/activity/starring#about-the-starring-api) and it would be really nice to use this library for it. I'd be happy to contribute a new module called `stars` that would effectively cover the endpoints exposed by the GitHub starring API. Hopefully this would be useful to others as well 🤞 

Is there a contributing guide or can I just fork and create a PR?

**Comment by lineville** [comment]
After taking a closer look, it probably makes more sense to just add a few more methods to the `repos` module rather than creating a separate module

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Generally octocrab follows octokit's organisation in terms where to put methods, so I would just follow that as a guideline to make a PR.

**Comment by lineville** [comment]
@XAMPPRocky I opened up a PR, it could use some 👀 if you get a chance 🙏
