### ISSUE TITLE
pull_request.edited events are deserialized into UnknownEvent variant, not PullRequestEvent

### ISSUE THREAD

**Issue by siketyan** [XAMPPRocky/octocrab#227]
I tried to parse a GitHub Action event into a struct as follows:
```rust
use octocrab::models::events::payload::EventPayload;

#[derive(Deserialize)]
pub struct Context {
    // ...(truncated)
    pub event: EventPayload,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_deserialize_pull_request_event() {
        let json = include_str!("../resources/pull-request-context.json");
        let context: Context = serde_json::from_str(json).unwrap();

        println!("{:?}", context.event);
    }
}
```

This test printed that context.event is `UnknownEvent`, not `PullRequestEvent` as I expected:
```
UnknownEvent(Object({"action": String("edited"), "changes": Object({}), "number": Number(10), "pull_request": Object({ // ...(truncated)
```

And here is the payload I used:

<details>
<summary>Payload Example</summary>
<pre>
{
  "token": "***",
  "job": "test",
  "ref": "refs/pull/10/merge",
  "sha": "a8725e47770eb23f05df4cd316f416acd5f2a875",
  "repository": "siketyan/sandbox",
  "repository_owner": "siketyan",
  "repository_owner_id": "12772118",
  "repositoryUrl": "git://github.com/siketyan/sandbox.git",
  "run_id": "2691957624",
  "run_number": "17",
  "retention_days": "90",
  "run_attempt": "1",
  "artifact_cache_size_limit": "10",
  "repository_visibility": "public",
  "repository_id": "513396540",
  "actor_id": "12772118",
  "actor": "siketyan",
  "workflow": "Access github context via JSON",
  "head_ref": "some-pr",
  "base_ref": "main",
  "event_name": "pull_request",
  "event": {
    "action": "edited",
    "changes": {},
    "number": 10,
    "pull_request": {
      "_links": {
        "comments": {
          "href": "https://api.github.com/repos/siketyan/sandbox/issues/10/comments"
        },
        "commits": {
          "href": "https://api.github.com/repos/siketyan/sandbox/pulls/10/commits"
        },
        "html": {
          "href": "https://github.com/siketyan/sandbox/pull/10"
        },
        "issue": {
          "href": "https://api.github.com/repos/siketyan/sandbox/issues/10"
        },
        "review_comment": {
          "href": "https://api.github.com/repos/siketyan/sandbox/pulls/comments{/number}"
        },
        "review_comments": {
          "href": "https://api.github.com/repos/siketyan/sandbox/pulls/10/comments"
        },
        "self": {
          "href": "https://api.github.com/repos/siketyan/sandbox/pulls/10"
        },
        "statuses": {
          "href": "https://api.github.com/repos/siketyan/sandbox/statuses/471313f4a8769101bc9aaf56eec710e7830d3e75"
        }
      },
      "active_lock_reason": null,
      "additions": 0,
      "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
        "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
        "followers_url": "https://api.github.com/users/siketyan/followers",
        "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
        "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/siketyan",
        "id": 12772118,
        "login": "siketyan",
        "node_id": "MDQ6VXNlcjEyNzcyMTE4",
        "organizations_url": "https://api.github.com/users/siketyan/orgs",
        "received_events_url": "https://api.github.com/users/siketyan/received_events",
        "repos_url": "https://api.github.com/users/siketyan/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/siketyan"
      },
      "assignees": [
        {
          "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
          "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
          "followers_url": "https://api.github.com/users/siketyan/followers",
          "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
          "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/siketyan",
          "id": 12772118,
          "login": "siketyan",
          "node_id": "MDQ6VXNlcjEyNzcyMTE4",
          "organizations_url": "https://api.github.com/users/siketyan/orgs",
          "received_events_url": "https://api.github.com/users/siketyan/received_events",
          "repos_url": "https://api.github.com/users/siketyan/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
          "type": "User",
          "url": "https://api.github.com/users/siketyan"
        }
      ],
      "author_association": "OWNER",
      "auto_merge": null,
      "base": {
        "label": "siketyan:main",
        "ref": "main",
        "repo": {
          "allow_auto_merge": false,
          "allow_forking": true,
          "allow_merge_commit": true,
          "allow_rebase_merge": true,
          "allow_squash_merge": true,
          "allow_update_branch": false,
          "archive_url": "https://api.github.com/repos/siketyan/sandbox/{archive_format}{/ref}",
          "archived": false,
          "assignees_url": "https://api.github.com/repos/siketyan/sandbox/assignees{/user}",
          "blobs_url": "https://api.github.com/repos/siketyan/sandbox/git/blobs{/sha}",
          "branches_url": "https://api.github.com/repos/siketyan/sandbox/branches{/branch}",
          "clone_url": "https://github.com/siketyan/sandbox.git",
          "collaborators_url": "https://api.github.com/repos/siketyan/sandbox/collaborators{/collaborator}",
          "comments_url": "https://api.github.com/repos/siketyan/sandbox/comments{/number}",
          "commits_url": "https://api.github.com/repos/siketyan/sandbox/commits{/sha}",
          "compare_url": "https://api.github.com/repos/siketyan/sandbox/compare/{base}...{head}",
          "contents_url": "https://api.github.com/repos/siketyan/sandbox/contents/{+path}",
          "contributors_url": "https://api.github.com/repos/siketyan/sandbox/contributors",
          "created_at": "2022-07-13T05:49:42Z",
          "default_branch": "main",
          "delete_branch_on_merge": false,
          "deployments_url": "https://api.github.com/repos/siketyan/sandbox/deployments",
          "description": null,
          "disabled": false,
          "downloads_url": "https://api.github.com/repos/siketyan/sandbox/downloads",
          "events_url": "https://api.github.com/repos/siketyan/sandbox/events",
          "fork": false,
          "forks": 0,
          "forks_count": 0,
          "forks_url": "https://api.github.com/repos/siketyan/sandbox/forks",
          "full_name": "siketyan/sandbox",
          "git_commits_url": "https://api.github.com/repos/siketyan/sandbox/git/commits{/sha}",
          "git_refs_url": "https://api.github.com/repos/siketyan/sandbox/git/refs{/sha}",
          "git_tags_url": "https://api.github.com/repos/siketyan/sandbox/git/tags{/sha}",
          "git_url": "git://github.com/siketyan/sandbox.git",
          "has_downloads": true,
          "has_issues": true,
          "has_pages": false,
          "has_projects": true,
          "has_wiki": true,
          "homepage": null,
          "hooks_url": "https://api.github.com/repos/siketyan/sandbox/hooks",
          "html_url": "https://github.com/siketyan/sandbox",
          "id": 513396540,
          "is_template": false,
          "issue_comment_url": "https://api.github.com/repos/siketyan/sandbox/issues/comments{/number}",
          "issue_events_url": "https://api.github.com/repos/siketyan/sandbox/issues/events{/number}",
          "issues_url": "https://api.github.com/repos/siketyan/sandbox/issues{/number}",
          "keys_url": "https://api.github.com/repos/siketyan/sandbox/keys{/key_id}",
          "labels_url": "https://api.github.com/repos/siketyan/sandbox/labels{/name}",
          "language": null,
          "languages_url": "https://api.github.com/repos/siketyan/sandbox/languages",
          "license": null,
          "merges_url": "https://api.github.com/repos/siketyan/sandbox/merges",
          "milestones_url": "https://api.github.com/repos/siketyan/sandbox/milestones{/number}",
          "mirror_url": null,
          "name": "sandbox",
          "node_id": "R_kgDOHpnPPA",
          "notifications_url": "https://api.github.com/repos/siketyan/sandbox/notifications{?since,all,participating}",
          "open_issues": 1,
          "open_issues_count": 1,
          "owner": {
            "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
            "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
            "followers_url": "https://api.github.com/users/siketyan/followers",
            "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
            "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/siketyan",
            "id": 12772118,
            "login": "siketyan",
            "node_id": "MDQ6VXNlcjEyNzcyMTE4",
            "organizations_url": "https://api.github.com/users/siketyan/orgs",
            "received_events_url": "https://api.github.com/users/siketyan/received_events",
            "repos_url": "https://api.github.com/users/siketyan/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/siketyan"
          },
          "private": false,
          "pulls_url": "https://api.github.com/repos/siketyan/sandbox/pulls{/number}",
          "pushed_at": "2022-07-18T16:22:01Z",
          "releases_url": "https://api.github.com/repos/siketyan/sandbox/releases{/id}",
          "size": 11,
          "ssh_url": "git@github.com:siketyan/sandbox.git",
          "stargazers_count": 0,
          "stargazers_url": "https://api.github.com/repos/siketyan/sandbox/stargazers",
          "statuses_url": "https://api.github.com/repos/siketyan/sandbox/statuses/{sha}",
          "subscribers_url": "https://api.github.com/repos/siketyan/sandbox/subscribers",
          "subscription_url": "https://api.github.com/repos/siketyan/sandbox/subscription",
          "svn_url": "https://github.com/siketyan/sandbox",
          "tags_url": "https://api.github.com/repos/siketyan/sandbox/tags",
          "teams_url": "https://api.github.com/repos/siketyan/sandbox/teams",
          "topics": [],
          "trees_url": "https://api.github.com/repos/siketyan/sandbox/git/trees{/sha}",
          "updated_at": "2022-07-13T05:49:42Z",
          "url": "https://api.github.com/repos/siketyan/sandbox",
          "use_squash_pr_title_as_default": false,
          "visibility": "public",
          "watchers": 0,
          "watchers_count": 0,
          "web_commit_signoff_required": false
        },
        "sha": "a0f3aee56297fe68a20b0711a458804ef38ff109",
        "user": {
          "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
          "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
          "followers_url": "https://api.github.com/users/siketyan/followers",
          "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
          "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/siketyan",
          "id": 12772118,
          "login": "siketyan",
          "node_id": "MDQ6VXNlcjEyNzcyMTE4",
          "organizations_url": "https://api.github.com/users/siketyan/orgs",
          "received_events_url": "https://api.github.com/users/siketyan/received_events",
          "repos_url": "https://api.github.com/users/siketyan/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
          "type": "User",
          "url": "https://api.github.com/users/siketyan"
        }
      },
      "body": "- [ ] aaa\r\n- [x] bbb",
      "changed_files": 0,
      "closed_at": null,
      "comments": 0,
      "comments_url": "https://api.github.com/repos/siketyan/sandbox/issues/10/comments",
      "commits": 1,
      "commits_url": "https://api.github.com/repos/siketyan/sandbox/pulls/10/commits",
      "created_at": "2022-07-18T16:22:01Z",
      "deletions": 0,
      "diff_url": "https://github.com/siketyan/sandbox/pull/10.diff",
      "draft": false,
      "head": {
        "label": "siketyan:some-pr",
        "ref": "some-pr",
        "repo": {
          "allow_auto_merge": false,
          "allow_forking": true,
          "allow_merge_commit": true,
          "allow_rebase_merge": true,
          "allow_squash_merge": true,
          "allow_update_branch": false,
          "archive_url": "https://api.github.com/repos/siketyan/sandbox/{archive_format}{/ref}",
          "archived": false,
          "assignees_url": "https://api.github.com/repos/siketyan/sandbox/assignees{/user}",
          "blobs_url": "https://api.github.com/repos/siketyan/sandbox/git/blobs{/sha}",
          "branches_url": "https://api.github.com/repos/siketyan/sandbox/branches{/branch}",
          "clone_url": "https://github.com/siketyan/sandbox.git",
          "collaborators_url": "https://api.github.com/repos/siketyan/sandbox/collaborators{/collaborator}",
          "comments_url": "https://api.github.com/repos/siketyan/sandbox/comments{/number}",
          "commits_url": "https://api.github.com/repos/siketyan/sandbox/commits{/sha}",
          "compare_url": "https://api.github.com/repos/siketyan/sandbox/compare/{base}...{head}",
          "contents_url": "https://api.github.com/repos/siketyan/sandbox/contents/{+path}",
          "contributors_url": "https://api.github.com/repos/siketyan/sandbox/contributors",
          "created_at": "2022-07-13T05:49:42Z",
          "default_branch": "main",
          "delete_branch_on_merge": false,
          "deployments_url": "https://api.github.com/repos/siketyan/sandbox/deployments",
          "description": null,
          "disabled": false,
          "downloads_url": "https://api.github.com/repos/siketyan/sandbox/downloads",
          "events_url": "https://api.github.com/repos/siketyan/sandbox/events",
          "fork": false,
          "forks": 0,
          "forks_count": 0,
          "forks_url": "https://api.github.com/repos/siketyan/sandbox/forks",
          "full_name": "siketyan/sandbox",
          "git_commits_url": "https://api.github.com/repos/siketyan/sandbox/git/commits{/sha}",
          "git_refs_url": "https://api.github.com/repos/siketyan/sandbox/git/refs{/sha}",
          "git_tags_url": "https://api.github.com/repos/siketyan/sandbox/git/tags{/sha}",
          "git_url": "git://github.com/siketyan/sandbox.git",
          "has_downloads": true,
          "has_issues": true,
          "has_pages": false,
          "has_projects": true,
          "has_wiki": true,
          "homepage": null,
          "hooks_url": "https://api.github.com/repos/siketyan/sandbox/hooks",
          "html_url": "https://github.com/siketyan/sandbox",
          "id": 513396540,
          "is_template": false,
          "issue_comment_url": "https://api.github.com/repos/siketyan/sandbox/issues/comments{/number}",
          "issue_events_url": "https://api.github.com/repos/siketyan/sandbox/issues/events{/number}",
          "issues_url": "https://api.github.com/repos/siketyan/sandbox/issues{/number}",
          "keys_url": "https://api.github.com/repos/siketyan/sandbox/keys{/key_id}",
          "labels_url": "https://api.github.com/repos/siketyan/sandbox/labels{/name}",
          "language": null,
          "languages_url": "https://api.github.com/repos/siketyan/sandbox/languages",
          "license": null,
          "merges_url": "https://api.github.com/repos/siketyan/sandbox/merges",
          "milestones_url": "https://api.github.com/repos/siketyan/sandbox/milestones{/number}",
          "mirror_url": null,
          "name": "sandbox",
          "node_id": "R_kgDOHpnPPA",
          "notifications_url": "https://api.github.com/repos/siketyan/sandbox/notifications{?since,all,participating}",
          "open_issues": 1,
          "open_issues_count": 1,
          "owner": {
            "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
            "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
            "followers_url": "https://api.github.com/users/siketyan/followers",
            "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
            "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/siketyan",
            "id": 12772118,
            "login": "siketyan",
            "node_id": "MDQ6VXNlcjEyNzcyMTE4",
            "organizations_url": "https://api.github.com/users/siketyan/orgs",
            "received_events_url": "https://api.github.com/users/siketyan/received_events",
            "repos_url": "https://api.github.com/users/siketyan/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/siketyan"
          },
          "private": false,
          "pulls_url": "https://api.github.com/repos/siketyan/sandbox/pulls{/number}",
          "pushed_at": "2022-07-18T16:22:01Z",
          "releases_url": "https://api.github.com/repos/siketyan/sandbox/releases{/id}",
          "size": 11,
          "ssh_url": "git@github.com:siketyan/sandbox.git",
          "stargazers_count": 0,
          "stargazers_url": "https://api.github.com/repos/siketyan/sandbox/stargazers",
          "statuses_url": "https://api.github.com/repos/siketyan/sandbox/statuses/{sha}",
          "subscribers_url": "https://api.github.com/repos/siketyan/sandbox/subscribers",
          "subscription_url": "https://api.github.com/repos/siketyan/sandbox/subscription",
          "svn_url": "https://github.com/siketyan/sandbox",
          "tags_url": "https://api.github.com/repos/siketyan/sandbox/tags",
          "teams_url": "https://api.github.com/repos/siketyan/sandbox/teams",
          "topics": [],
          "trees_url": "https://api.github.com/repos/siketyan/sandbox/git/trees{/sha}",
          "updated_at": "2022-07-13T05:49:42Z",
          "url": "https://api.github.com/repos/siketyan/sandbox",
          "use_squash_pr_title_as_default": false,
          "visibility": "public",
          "watchers": 0,
          "watchers_count": 0,
          "web_commit_signoff_required": false
        },
        "sha": "471313f4a8769101bc9aaf56eec710e7830d3e75",
        "user": {
          "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
          "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
          "followers_url": "https://api.github.com/users/siketyan/followers",
          "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
          "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/siketyan",
          "id": 12772118,
          "login": "siketyan",
          "node_id": "MDQ6VXNlcjEyNzcyMTE4",
          "organizations_url": "https://api.github.com/users/siketyan/orgs",
          "received_events_url": "https://api.github.com/users/siketyan/received_events",
          "repos_url": "https://api.github.com/users/siketyan/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
          "type": "User",
          "url": "https://api.github.com/users/siketyan"
        }
      },
      "html_url": "https://github.com/siketyan/sandbox/pull/10",
      "id": 999607039,
      "issue_url": "https://api.github.com/repos/siketyan/sandbox/issues/10",
      "labels": [],
      "locked": false,
      "maintainer_can_modify": false,
      "merge_commit_sha": "a8725e47770eb23f05df4cd316f416acd5f2a875",
      "mergeable": true,
      "mergeable_state": "clean",
      "merged": false,
      "merged_at": null,
      "merged_by": null,
      "milestone": null,
      "node_id": "PR_kwDOHpnPPM47lMr_",
      "number": 10,
      "patch_url": "https://github.com/siketyan/sandbox/pull/10.patch",
      "rebaseable": true,
      "requested_reviewers": [],
      "requested_teams": [],
      "review_comment_url": "https://api.github.com/repos/siketyan/sandbox/pulls/comments{/number}",
      "review_comments": 0,
      "review_comments_url": "https://api.github.com/repos/siketyan/sandbox/pulls/10/comments",
      "state": "open",
      "statuses_url": "https://api.github.com/repos/siketyan/sandbox/statuses/471313f4a8769101bc9aaf56eec710e7830d3e75",
      "title": "chore: Some changes",
      "updated_at": "2022-07-18T16:22:21Z",
      "url": "https://api.github.com/repos/siketyan/sandbox/pulls/10",
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
        "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
        "followers_url": "https://api.github.com/users/siketyan/followers",
        "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
        "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/siketyan",
        "id": 12772118,
        "login": "siketyan",
        "node_id": "MDQ6VXNlcjEyNzcyMTE4",
        "organizations_url": "https://api.github.com/users/siketyan/orgs",
        "received_events_url": "https://api.github.com/users/siketyan/received_events",
        "repos_url": "https://api.github.com/users/siketyan/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/siketyan"
      }
    },
    "repository": {
      "allow_forking": true,
      "archive_url": "https://api.github.com/repos/siketyan/sandbox/{archive_format}{/ref}",
      "archived": false,
      "assignees_url": "https://api.github.com/repos/siketyan/sandbox/assignees{/user}",
      "blobs_url": "https://api.github.com/repos/siketyan/sandbox/git/blobs{/sha}",
      "branches_url": "https://api.github.com/repos/siketyan/sandbox/branches{/branch}",
      "clone_url": "https://github.com/siketyan/sandbox.git",
      "collaborators_url": "https://api.github.com/repos/siketyan/sandbox/collaborators{/collaborator}",
      "comments_url": "https://api.github.com/repos/siketyan/sandbox/comments{/number}",
      "commits_url": "https://api.github.com/repos/siketyan/sandbox/commits{/sha}",
      "compare_url": "https://api.github.com/repos/siketyan/sandbox/compare/{base}...{head}",
      "contents_url": "https://api.github.com/repos/siketyan/sandbox/contents/{+path}",
      "contributors_url": "https://api.github.com/repos/siketyan/sandbox/contributors",
      "created_at": "2022-07-13T05:49:42Z",
      "default_branch": "main",
      "deployments_url": "https://api.github.com/repos/siketyan/sandbox/deployments",
      "description": null,
      "disabled": false,
      "downloads_url": "https://api.github.com/repos/siketyan/sandbox/downloads",
      "events_url": "https://api.github.com/repos/siketyan/sandbox/events",
      "fork": false,
      "forks": 0,
      "forks_count": 0,
      "forks_url": "https://api.github.com/repos/siketyan/sandbox/forks",
      "full_name": "siketyan/sandbox",
      "git_commits_url": "https://api.github.com/repos/siketyan/sandbox/git/commits{/sha}",
      "git_refs_url": "https://api.github.com/repos/siketyan/sandbox/git/refs{/sha}",
      "git_tags_url": "https://api.github.com/repos/siketyan/sandbox/git/tags{/sha}",
      "git_url": "git://github.com/siketyan/sandbox.git",
      "has_downloads": true,
      "has_issues": true,
      "has_pages": false,
      "has_projects": true,
      "has_wiki": true,
      "homepage": null,
      "hooks_url": "https://api.github.com/repos/siketyan/sandbox/hooks",
      "html_url": "https://github.com/siketyan/sandbox",
      "id": 513396540,
      "is_template": false,
      "issue_comment_url": "https://api.github.com/repos/siketyan/sandbox/issues/comments{/number}",
      "issue_events_url": "https://api.github.com/repos/siketyan/sandbox/issues/events{/number}",
      "issues_url": "https://api.github.com/repos/siketyan/sandbox/issues{/number}",
      "keys_url": "https://api.github.com/repos/siketyan/sandbox/keys{/key_id}",
      "labels_url": "https://api.github.com/repos/siketyan/sandbox/labels{/name}",
      "language": null,
      "languages_url": "https://api.github.com/repos/siketyan/sandbox/languages",
      "license": null,
      "merges_url": "https://api.github.com/repos/siketyan/sandbox/merges",
      "milestones_url": "https://api.github.com/repos/siketyan/sandbox/milestones{/number}",
      "mirror_url": null,
      "name": "sandbox",
      "node_id": "R_kgDOHpnPPA",
      "notifications_url": "https://api.github.com/repos/siketyan/sandbox/notifications{?since,all,participating}",
      "open_issues": 1,
      "open_issues_count": 1,
      "owner": {
        "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
        "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
        "followers_url": "https://api.github.com/users/siketyan/followers",
        "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
        "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/siketyan",
        "id": 12772118,
        "login": "siketyan",
        "node_id": "MDQ6VXNlcjEyNzcyMTE4",
        "organizations_url": "https://api.github.com/users/siketyan/orgs",
        "received_events_url": "https://api.github.com/users/siketyan/received_events",
        "repos_url": "https://api.github.com/users/siketyan/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/siketyan"
      },
      "private": false,
      "pulls_url": "https://api.github.com/repos/siketyan/sandbox/pulls{/number}",
      "pushed_at": "2022-07-18T16:22:01Z",
      "releases_url": "https://api.github.com/repos/siketyan/sandbox/releases{/id}",
      "size": 11,
      "ssh_url": "git@github.com:siketyan/sandbox.git",
      "stargazers_count": 0,
      "stargazers_url": "https://api.github.com/repos/siketyan/sandbox/stargazers",
      "statuses_url": "https://api.github.com/repos/siketyan/sandbox/statuses/{sha}",
      "subscribers_url": "https://api.github.com/repos/siketyan/sandbox/subscribers",
      "subscription_url": "https://api.github.com/repos/siketyan/sandbox/subscription",
      "svn_url": "https://github.com/siketyan/sandbox",
      "tags_url": "https://api.github.com/repos/siketyan/sandbox/tags",
      "teams_url": "https://api.github.com/repos/siketyan/sandbox/teams",
      "topics": [],
      "trees_url": "https://api.github.com/repos/siketyan/sandbox/git/trees{/sha}",
      "updated_at": "2022-07-13T05:49:42Z",
      "url": "https://api.github.com/repos/siketyan/sandbox",
      "visibility": "public",
      "watchers": 0,
      "watchers_count": 0,
      "web_commit_signoff_required": false
    },
    "sender": {
      "avatar_url": "https://avatars.githubusercontent.com/u/12772118?v=4",
      "events_url": "https://api.github.com/users/siketyan/events{/privacy}",
      "followers_url": "https://api.github.com/users/siketyan/followers",
      "following_url": "https://api.github.com/users/siketyan/following{/other_user}",
      "gists_url": "https://api.github.com/users/siketyan/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/siketyan",
      "id": 12772118,
      "login": "siketyan",
      "node_id": "MDQ6VXNlcjEyNzcyMTE4",
      "organizations_url": "https://api.github.com/users/siketyan/orgs",
      "received_events_url": "https://api.github.com/users/siketyan/received_events",
      "repos_url": "https://api.github.com/users/siketyan/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/siketyan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/siketyan/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/siketyan"
    }
  },
  "server_url": "https://github.com",
  "api_url": "https://api.github.com",
  "graphql_url": "https://api.github.com/graphql",
  "ref_name": "10/merge",
  "ref_protected": false,
  "ref_type": "branch",
  "secret_source": "Actions",
  "workspace": "/home/runner/work/sandbox/sandbox",
  "action": "__siketyan_automan",
  "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
  "action_repository": "siketyan/automan",
  "action_ref": "main",
  "path": "/home/runner/work/_temp/_runner_file_commands/add_path_25d635c2-939b-4cea-a168-1fb16f6d974e",
  "env": "/home/runner/work/_temp/_runner_file_commands/set_env_25d635c2-939b-4cea-a168-1fb16f6d974e",
  "step_summary": "/home/runner/work/_temp/_runner_file_commands/step_summary_25d635c2-939b-4cea-a168-1fb16f6d974e"
}
</pre>
</details>

It seems `EventPayload` is not typed correctly for this type of event.
Tested with octocrab v0.16.0.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Seems pretty straightforward to fix, if anyone wants to make a PR I'd be happy to accept it.
