### ISSUE TITLE
Support device authentication flow

### ISSUE THREAD

**Issue by iwahbe** [XAMPPRocky/octocrab#247]
The project I'm working on requires a [`device flow`](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow) login. I have a solution that works with octocrab to handle this. Would `octocrab` be interested in supporting this authentication workflow directly? If so I can submit a PR.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes, I would be interested, in general if it's part of the GitHub API, it should be part of octocrab.
