### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jakubadamw** [XAMPPRocky/octocrab#249]
Hello, would you please be able to release a new version? https://github.com/XAMPPRocky/octocrab/pull/239 is quite an important fix. Thank you.

**Comment by suryapandian** [comment]
we are also waiting for a release because of the changes we did in another PR :)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'll try to find time to cut a release this weekend. In the meantime, [sponsoring me on github](https://github.com/sponsors/XAMPPRocky) is always appreciated as it directly helps me to dedicate more time to personal projects like octocrab and release changes more often. 🙂

**Comment by XAMPPRocky** [comment]
Sorry for the delay but there's a new `0.18.0` version released now.
