### ISSUE TITLE
How to get the "starred_at" field with list_stargazers?

### ISSUE THREAD

**Issue by yanshay** [XAMPPRocky/octocrab#268]
Github's ListGazer supports fetching the time when a gazer starred a repo (https://docs.github.com/en/rest/activity/starring#list-repositories-being-starred).

For that need to add an Accept Header to the request and then the response structure changes, so instead of a list of users:
`
[
  {
    "login": "octocat",
    "id": 1,
    ...
  }
  ...
]
`

it responds with a list that looks like this:
`
[
  {
    "starred_at": "2011-01-16T19:06:43Z",
    "user": {
      "login": "octocat",
      "id": 1,
      ...
   }
   ...
]
`

How can I access this different method of calling to retrieve the "starred_at" field?

I'm also good with extending Octocrab for this but couldn't figure out how to do it.

Thanks

**Comment by lineville** [comment]
Thanks for creating this issue, I wrote the `list_stargazers` endpoint a couple months back, refreshing my memory on this. I see in the docs the bit about needing to add a header with the value `application/vnd.github.star+json` and then that will include the `starred_at` field in the payload. It looks like the `User` model being returned already has a `starred_at` field on it, so no need to update the model, I think just passing in that custom header is all that's needed is to pass in that extra header. I could take a look into it this weekend, but feel free to go for it if you want!

**Comment by XAMPPRocky** [comment]
We should probably add that header when you call that method, like has been done with others.

**Comment by yanshay** [comment]
>  It looks like the `User` model being returned already has a `starred_at` field on it, so no need to update the model

I don't see a 'starred_at' field in the User model, only 'starred_url'.
Would there be any implications adding it as optional? I haven't checked but I assume it's also used by other API's.
Also - the response is of different structure. The actual User in the new response is wrapped with another structure. It only adds the starred_at and could probably be added in the User but I don't know if (1) is this a good approach? and (2) how to get serde to deserialize the hierarchy into a flat structure.

> I think just passing in that custom header is all that's needed. I could take a look into it this weekend, but feel free to go for it if you want!

When looking into the code I see headers can only be added in the _get method (or globally to the builder() but that would be global not just to list_stargazers method and might have side effects).
Adding it to the _get would require adding a parameter for headers but would probably be a breaking change? Is there a way I don't see to add headers from the send method for just that call?
Locally I added get_with_headers and _get_with_headers, I could have the original get and _get use those to keep backwards compatibility, but want to know first if that's the right thing to do.

**Comment by XAMPPRocky** [comment]
You can reference the inner client directly like has been done here.

https://github.com/XAMPPRocky/octocrab/blob/13838dcf6526c14b1789cb80918900b4f5254689/src/api/repos/generate.rs#L61-L66

**Comment by yanshay** [comment]
> You can reference the inner client directly like has been done here.

Isn't what is taking place there is practically duplicating the get and _get into the method?
So in my case I'd also need to call the from_response in the function.

**Comment by yanshay** [comment]
Submitted PR to resolve this issue.
