### ISSUE TITLE
Add Gists API

### ISSUE THREAD

**Issue by XAMPPRocky** [XAMPPRocky/octocrab#27]

**Comment by envp** [comment]
@XAMPPRocky is there still interest in reviewing a contribution for this?

**Comment by XAMPPRocky** [comment]
@envp Contibutions are always welcome and encouraged 🙂

**Comment by envp** [comment]
> @envp Contibutions are always welcome and encouraged 🙂

Thanks! I've made a couple of PRs to familiarize myself.

**Comment by envp** [comment]
I've tried to tabulate what the `TODO`s would be acc to [GitHub API docs (API Version 2022-11-28)][1]

- [X] Create a gist (`POST /gists`)
- [X] Get a gist (`GET /gists/{gist_id}`)
- [X] Update a gist (`PATCH /gists/{gist_id}`)
- [X] List gist commits (`GET /gists/{gist_id}/commits`)
- [X] List gists for authenticated user (`GET /gists`)
- [ ] List all public gists (`GET /gists`)
- [ ] List public gists (`GET /gists/public`)
- [ ] List starred gists (`GET /gists/starred`)
- [ ] Delete a gist (`DELETE /gists/{gist_id}`)
- [ ] List gist forks (`GET /gists/{gist_id}/forks`)
- [ ] Fork a gist (`POST /gists/{gist_id}/forks`)
- [ ] Check if a gist is starred (`GET /gists/{gist_id}/star`)
- [ ] Star a gist (`PUT /gists/{gist_id}/star`)
- [ ] Unstar a gist (`DELETE /gists/{gist_id}/star`)
- [ ] Get a gist revision (`GET /gists/{gist_id}/{sha}`)
- [ ] List gists for a user (`GET /users/{username}/gists`)


[1]: https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#create-a-gist

let me know if I missed something.

**Comment by envp** [comment]
@XAMPPRocky Some of github's APIs return an empty response body, these can't be deserialized with the current `FromResponse` trait which assume there's always valid JSON.

I tried implementing `FromResponse for ()` so callers can ask to discard the response body. However, that conflicts with the current implementation.  WDYT is a good way to handle this?

**Comment by XAMPPRocky** [comment]
@envp There are other parts of the API that do that, in general for those you should use the `_` prefixed versions like `_put` that do no processing on the response.

**Comment by envp** [comment]
@XAMPPRocky Not sure how important these three are. I personally don't have a use-case for the bulk gist retrival endpoints (`GET /gists[/public]`). And `GET /users/{username}/gists` seems to (slightly) overlap with the endpoint for retrieving the authenticated user's gists.

```
List gists for a user (GET /users/{username}/gists)
List all public gists (GET /gists)
List public gists (GET /gists/public)
```

Will continue on these if you think they're useful to have. Thanks again :)

**Comment by XAMPPRocky** [comment]
> Will continue on these if you think they're useful to have.

In general the goal of the project is to support as much of GitHub's API as possible, so adding support for these APIs is always useful and appreciated if you want to contribute them. 🙂
