### ISSUE TITLE
create commit comments?

### ISSUE THREAD

**Issue by Roger-luo** [XAMPPRocky/octocrab#299]
Hi, I'm wondering if the `create_comment` API could also support creating on commits? since it's part of github's API. 

for reference: https://docs.github.com/en/rest/commits/comments?apiVersion=2022-11-28

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Anything that's part of the GitHub API should be included, I don't have the time to implement it myself, but I'm happy to accept a PR.
