### ISSUE TITLE
Committer is spelled wrong

### ISSUE THREAD

**Issue by orhun** [XAMPPRocky/octocrab#316]
See:

https://github.com/XAMPPRocky/octocrab/blob/16134a8f1f1c602ab8f4622d789ea94f9b03b464/src/models/repos.rs#L53

It should be `committer` instead of `comitter`. I'm afraid changing this will result in a breaking change.

I can submit a PR to change it if applicable.

**Comment by XAMPPRocky** [comment]
> I can submit a PR to change it if applicable.

Thank you for your issue! Please do 🙂
