### ISSUE TITLE
Does `octocrab` v0.20.0 support rustls?

### ISSUE THREAD

**Issue by koyashiro** [XAMPPRocky/octocrab#341]
In v0.20.0 `reqwest` has been replaced by `http`, `hyper` and `tower`, but the `rustls` features flag that was present before seems to [have been removed](https://github.com/XAMPPRocky/octocrab/pull/297).

Has `rustls` support been removed?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I may be wrong but I believe the old feature wasn't relevant anymore with the removal of reqwest, users should be able to provide their own HTTP client with whatever TLS implementation they prefer.

**Comment by koyashiro** [comment]
I appreciate your prompt reply.

By referring to [`examples/custom_client.rs`](https://github.com/XAMPPRocky/octocrab/blob/v0.20.0/examples/custom_client.rs), my problem was solved.
