### ISSUE TITLE
Failed to get release JSON error

### ISSUE THREAD

**Issue by DrProfSgtMrJ** [XAMPPRocky/octocrab#361]
I know there was a similar issue, but recently, when attempting to get a release, I received this error: 
`Error: Failed to get release JSON Error in assets[0].uploader: missing field `name` at line 1 column 2898`

Should the name field be optional in the `CommitAuthor` struct? The name not being there is a valid case so shouldn't it be accounted for in the model? 

I'm sorry if this is not well put. I'm new to submitting issues.

**Comment by DrProfSgtMrJ** [comment]
I'm closing this cause I realized that it has been updated in the code it just isn't updated in the released crate I supposed.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'll make a new release today or tomorrow with the fix.
