### ISSUE TITLE
Notifications lists returns `InvalidUri`

### ISSUE THREAD

**Issue by DanielVoogsgerd** [XAMPPRocky/octocrab#363]
When using `NotificationsHandler.lists()` a `InvalidUri` Error is returned.

This also happens in the `notifications` example.

I suppose a leading `/` was missed in [src/api/activity/notifications.rs#L252](https://github.com/XAMPPRocky/octocrab/blob/44c251d/src/api/activity/notifications.rs#L252) during #297

**Comment by XAMPPRocky** [comment]
Thank you for your issue! If someone wants to write quick PR to fix it, we can merge and release it today.

**Comment by DanielVoogsgerd** [comment]
Done, see #364
