### ISSUE TITLE
`hyper/tcp` leads to compilation issues on WebAssembly

### ISSUE THREAD

**Issue by j178** [XAMPPRocky/octocrab#366]
Hi,

octocrab enables `hyper/tcp` by default, it uses `socket2`, which does not compile on wasm. I am unsure about the necessity of enabling `hyper/tcp`. Is it possible to remove or find an alternative for it to resolve the compilation issue?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This is something I want to address, but right now I'm not sure of the best way to resolve it I think ideally this library would be HTTP client agnostic to avoid this situation, and that's the solution I'd like to pursue long term, but right now I'm not sure how to achieve that yet.

**Comment by patrickelectric** [comment]
looking forward for this feature!

**Comment by XAMPPRocky** [comment]
@patrickelectric Yes, the problem with that crate is that it uses `reqwest` which means it's even more incompatible with the rest of the HTTP ecosystem even though it provides `wasi` support. It's unfortunate that two crates by the same author are so incompatible with each other, but that's the current state of the world. Ideally you'd be able to pass in a `reqwest::Client` to be able to achieve the same result as that fork, but you currently cannot.
