### ISSUE TITLE
Support API on same domain where github server located (enterprize installations)

### ISSUE THREAD

**Issue by rumatoest** [XAMPPRocky/octocrab#37]
In our github enterprise installation we have domain like https://repository.company.com/ and no other domains.

API is available under URI https://repository.company.com/api/v3/

There is no way to tell octocrab to use this URI as prefix for API it always strip down API URI to https://repository.company.com

Right now I can use only low level octocrab API where I have to provide exact URI manually 
```
octointance.get("https://repository.company.com/api/v3/search/code", Some(&params))
```

**Comment by XAMPPRocky** [comment]
@rumatoest Thank you for your issue! You can set the base url using `OctocrabBuilder::base_url`. https://docs.rs/octocrab/0.6.1/octocrab/struct.OctocrabBuilder.html#method.base_url

**Comment by rumatoest** [comment]
The thing is that is does not work this way.
When I add `https://repository.company.com/api/v3/search/code` via `OctocrabBuilder::base_url` it would eventually show in debug logs stripped URL like `https://repository.company.com/repos/user/mycode/license` instead `https://repository.company.com/api/v3/repos/user/mycode/license`

**Comment by XAMPPRocky** [comment]
@rumatoest You’re using it incorrectly. The base url is just `https://repository.company.com/api/v3` and then you would just call `search` on `Octocrab` or you could use `octocrab.get(“/search/code”)`. https://docs.rs/octocrab/0.6.1/octocrab/struct.Octocrab.html#method.search
