### ISSUE TITLE
Authenticate on Behalf of a User

### ISSUE THREAD

**Issue by lswith** [XAMPPRocky/octocrab#374]
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-a-github-app-on-behalf-of-a-user

It seems that octocrab only supports:
- NoAuth
- BasicAuth
- PersonalToken
- Github App
- Github OAuth App

There is one more Authentication flow, which is as a GitHub app on behalf-of a user.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I don't have the time to add this currently but I would be able to review and merge a PR. 🙂
