### ISSUE TITLE
JSON Error in .: EOF when using octocrab.put()

### ISSUE THREAD

**Issue by aisrael** [XAMPPRocky/octocrab#382]
I'm trying to use the HTTP API, specifically the `put<R, A, B>(&self, route: A, body: Option<&B>) -> Result<R>` method, something like:

```
        let invite: RepositoryInvitation = octocrab
            .put(
                "/repos/gitsudo-io/test-repo-alpha/collaborators/aisrael",
                Some(&serde_json::json!({ "permission": "admin" })),
            )
```

Where `RepositoryInvitation` is a struct that has `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]` (like all the other Octocrab models).

However, while the API call itself succeeds (and I can verify that I'm added as an "admin" successfully), I get the following error:

```
JSON Error in .: EOF while parsing a value at line 1 column 0
Found at  0 <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate::h4073aa73c3c7d8c3
   /home/aisrael/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.4/src/backtrace_shim.rs:15
   snafu::GenerateImplicitData::generate_with_source::h24cb4b779d61e2d9
   /home/aisrael/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.4/src/lib.rs:1152
 1 <octocrab::error::JsonSnafu as snafu::IntoError<octocrab::error::Error>>::into_error::hbfbf6558ce87d392
   /home/aisrael/.cargo/registry/src/github.com-1ecc6299db9ec823/octocrab-0.21.0/src/error.rs:23
 2 <core::result::Result<T,E> as snafu::ResultExt<T,E>>::context::hede60ed24eb97778
   /home/aisrael/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.4/src/lib.rs:697
 3 <T as octocrab::from_response::FromResponse>::from_response::{{closure}}::h0088654792bb9177
   /home/aisrael/.cargo/registry/src/github.com-1ecc6299db9ec823/octocrab-0.21.0/src/from_response.rs:18
```

I've also tried `let () = octocrab.put(...)` and `let Option<()> = octocrab.put(...)` to try and specify an empty response body and thus avoid deserializing the output (the `PUT` API by default returns and empty response body, unless certain headers are present) but I still get the error. I've also tried `let resp: String = octocrab.put(...)` to try and return the response body as is without deserialization, with the same error.

Finally, I've verified that using `_put()`, for example:

```
        let result = octocrab
            ._put(
                "/repos/gitsudo-io/test-repo-alpha/collaborators/aisrael",
                Some(&serde_json::json!({ "permission": "admin" })),
            )
            .await;
```

Succeeds (and I can later retrieve the response body as a raw String).

Can anyone help point out what I may be missing?

**Comment by envp** [comment]
@aisrael 

If you don't care about the response data returned by the [PUT endpoint](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#add-a-repository-collaborator--code-samples), using the `_put` variant is the right way to execute the request.

Also, what does the equivalent curl command return?

```shell
curl -L \
  -X PUT \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/gitsudo-io/test-repo-alpha/collaborators/aisrael \
  -d '{"permission":"admin"}'
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! As @envp points out, this using `_put` is probably what you want because `put` assumes you have a JSON body, which is how most of the GitHub API operates, and for the corner cases that don't work like that, the `_` prefixed methods are what you should use as they don't do any pre or post processing on the HTTP request and response.

All of that being said, we should probably just add this endpoint to the semantic API so you don't have to worry about those details, if anyone wants to contribute a PR, I'd be happy to review and merge it.

**Comment by aisrael** [comment]
Thanks. The [endpoint itself](https://docs.github.com/en/rest/collaborators/collaborators#add-a-repository-collaborator) _may_ return a response body on a `201`, but can also return a `204` ("No Content").

So, for now, I guess I'll be sticking to `_put()` but I think this is something that the semantic API and the `put()` method in general will have to handle in the future, e.g. allow `Option<T>` for the response body (if it doesn't already do so).

**Comment by XAMPPRocky** [comment]
> but I think this is something that the semantic API and the put() method in general will have to handle in the future

`put` shouldn't handle it, the semantic API method should just use `_put` and handle this case specifically.
