### ISSUE TITLE
How to get reactions on an issue?

### ISSUE THREAD

**Issue by u9g** [XAMPPRocky/octocrab#400]
Hi, I'm currently using octocrab to make something that would allow me to see issues that have more than 50 thumbs up reactions. Currently I get the issues using the following code:
```rust
 executor::block_on(
    octocrab::instance()
        .issues(owner.to_string(), name.to_string())
        .list()
        .per_page(100)
        .send(),
)
.expect("to find issues")
```
I don't see any obvious way to get the reactions currently. How would I be able to get the reactions on the issues?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I could be wrong, you'd have to check the GitHub API, but I remember reactions being something that was only available in the GraphQL API, but that may have changed.

**Comment by u9g** [comment]
I looked a bit more, For anyone in the future: there's a reaction iterator:
```
let instance = octocrab::instance();
        let issue = instance.issues(repo_owner.to_string(), repo_name.to_string());
        let last_reactions = runtime()
            .block_on(issue.list_reactions(issue_id.0).per_page(100).send())
            .expect("expect to be able to get reactions");
```
