### ISSUE TITLE
bug: Graphql doesn't work `Body should be a JSON object`

### ISSUE THREAD

**Issue by marc2332** [XAMPPRocky/octocrab#401]
Hi, I am trying to make a graphql request but even the example snippet fails:

Code:
```rust
use octocrab::Octocrab;

#[tokio::main]
async fn main() {
    let token = std::env::var("GITHUB_TOKEN").expect("GITHUB_TOKEN env variable is required");

    let gh = Octocrab::builder().personal_token(token).build().unwrap();

    let response = gh
        .graphql::<serde_json::Value>("{ 'query': '{ viewer { login }}' }")
        .await;

    println!("{:?}", response);
}

```

Error:
```
GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/graphql"), errors: None, message: "Body should be a JSON object" },
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! The error is self-evident, you're passing a string and not a JSON object.

```rust
let response = gh
        .graphql(serde_json::json!({ "query": "{ viewer { login }}" }))
        .await;
```

**Comment by marc2332** [comment]
> ```rust
> let response = gh.graphql(serde_json::json!({ "query": "{ viewer { login }}" })).await;
> ```

Ah nice, I suggest you update the example code from https://github.com/XAMPPRocky/octocrab/blob/f2ce7986fc12c7084ff84bf3e022aa53b8dfa39f/src/lib.rs#L1038 so others don't have the same error as I did 👍 

Thank you 😄

**Comment by XAMPPRocky** [comment]
> Ah nice, I suggest you update the example code from

Thanks for the catch, I don't have the time right now, but if you wanted to make a quick Pr, I'd be happy to accept it 🙂

**Comment by marc2332** [comment]
> > Ah nice, I suggest you update the example code from
> 
> Thanks for the catch, I don't have the time right now, but if you wanted to make a quick Pr, I'd be happy to accept it 🙂

Ohh, no worries! I will make the PR asap 😄 👍 

Nice library btw, I like it!
