### ISSUE TITLE
Add `installation_id: Option<InstallationId>` to models::events::Event

### ISSUE THREAD

**Issue by gagbo** [XAMPPRocky/octocrab#407]
Hello,

I'm currently trying to write a wrapper library to write github applications that react to webhooks. One thing I noticed is that I can't currently access the installation ID from webhook payloads, although the API documentation says that `installation` information is [common in all webhook payloads](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-common-properties), just like the other fields currently living at the "top-level" of [`models::events::Event` structure](https://github.com/XAMPPRocky/octocrab/blob/f2ce7986fc12c7084ff84bf3e022aa53b8dfa39f/src/models/events.rs#L15-L27).

Would it be possible to add access to that id property? From the [current integration tests](https://github.com/XAMPPRocky/octocrab/blob/f2ce7986fc12c7084ff84bf3e022aa53b8dfa39f/tests/resources/workflow_run_event.json#L340), it looks like only the `id` property would be useful ("don't know, don't care" about the `node_id`); and having a `pub installation_id: Option<InstallationId>` in `Event` would be really really nice!

Thanks for the lib anyways,
Gerry

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I don't have to add it myself, but I would be happy to accept a PR that adds the property 🙂

**Comment by gagbo** [comment]
> Thank you for your issue! I don't have time to add it myself, but I would be happy to accept a PR that adds the property 🙂

Oh cool, I wasn't sure it was going to be accepted, I tried my hand at it (with a breaking API change, see the PR), I'll gladly take comments over it to change that (and maybe add support for the other common fields properly)

**Comment by XAMPPRocky** [comment]
> Oh cool, I wasn't sure it was going to be accepted

Contributions are always welcome and encouraged.  🙂
