### ISSUE TITLE
`IssueHandle::delete_label` panics

### ISSUE THREAD

**Issue by chorman0773** [XAMPPRocky/octocrab#456]
(Code is using `octocrab = "0.30.1"`)
When calling `IssueHandle::delete_label`, `IssueHandle` panics. This appears to be because it expects a response in Json format, but according to [github's documentation](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#delete-a-label), the endpoint does not return any data (on success, it yields 204 No Content).

**Comment by chorman0773** [comment]
Correction: It is returning an error, rather than panicking (the backtrace was throwing me off). However, the root cause of the issue remains: it's trying to parse a response that the API does not provide.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I don't have time to fix this myself right now, but the solution is simple, we just need use `_delete` instead of `delete` which doesn't try any of the parsing of the request.

**Comment by chorman0773** [comment]
I actually wrote a fix (running on the tool I was writing to find this),
and I'll file a PR later today.

**Comment by manchicken** [comment]
I think the PR I just submitted yesterday, #503 should resolve this.

**Comment by XAMPPRocky** [comment]
Thank you for your issue!
