### ISSUE TITLE
Why does `octocrab` need `tracing` as a feature?

### ISSUE THREAD

**Issue by suryapandian** [XAMPPRocky/octocrab#457]
Recently while working on [this](https://github.com/XAMPPRocky/octocrab/pull/454) PR, we noticed the below:

Octocrab octocrab tries to not download `tracing` libraries for users who do not use `tracing` feature. However,`tracing` downloaded by default by `hyper`. Since Octocrab depends on `hyper`, `tracing` library gets downloaded by default.

Unless all the upstream libraries have similar feature flag, the feature flag `tracing` of `octocrab` does not seem to have any benefit.

_Can we remove the `tracing` feature flag?_ if not, why?
If the feature flag serves other purposes, please let me know.

I am happy to work on this once you give your thoughts and direction 🙋‍♀️

**Comment by XAMPPRocky** [comment]
Thank you for your issue! You're right that it doesn't save a dependency currently. however there is a compile time and runtime cost to tracing/logging, that is removed with the feature.

Also the goal is to eventually remove the hyper dependency entirely so users can choose their HTTP client library, so it will be more relevant then.

**Comment by suryapandian** [comment]
> however there is a compile time and runtime cost to tracing/logging, that is removed with the feature.
wow! wasnt aware that simple tracing log statements could affect compile time and runtime.

Thanks for the clarification, closing this issue in that case. I have also raised an issue upstream https://github.com/hyperium/hyper/issues/3304 requesting them to feature flag `tracing`, i will probably try implementing that in hyper, not sure if it would be `good-first-issue` for me to pick up tho. 🤔

**Comment by XAMPPRocky** [comment]
To be clear, depending on your application, the cost is incredibly minimal and it will usually never be a bottleneck, but there's always some cost, and it can also add extra noise to logs you might not want.

**Comment by suryapandian** [comment]
Thanks for clarification
