### ISSUE TITLE
PullRequest → corresponding issue

### ISSUE THREAD

**Issue by Chris00** [XAMPPRocky/octocrab#473]
To comment on a pull request, one needs to use its [`issue_url` field](https://docs.rs/octocrab/0.31.2/octocrab/models/pulls/struct.PullRequest.html#structfield.issue_url), extract its issue _number_ and then use [`issues`](https://docs.rs/octocrab/0.31.2/octocrab/struct.Octocrab.html#method.issues)`(owner, repo).`[`create_comment`](https://docs.rs/octocrab/0.31.2/octocrab/issues/struct.IssueHandler.html#method.create_comment)`(number, body)` to add the comment.  A function
```rust
PullRequest::issue(&self) → IssueId
```
would be nice to have.  Note that `IssueId` was used in order to avoid mixing it with numbers coming from other sources but then some signatures should be updated such as 
```rust
pub async fn create_comment(
    &self,
    number: impl Into<IssueId>,
    body: impl AsRef<str>
) -> Result<Comment>
```
where `u64` should implement `Into<IssueId>` for convenience and backward compatibility.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Seems reasonable to me, if someone wants to make a PR for it, I would be happy to review it.

**Comment by Chris00** [comment]
@maflcko You are right, the IssueId is not the same as issue number.  I'll simply use `u64`.
