### ISSUE TITLE
Update arc-swap

### ISSUE THREAD

**Issue by dbanty** [XAMPPRocky/octocrab#48]
I get an error when attempting to install this package from cargo:

```
error: failed to select a version for the requirement `arc-swap = "^0.4.6"`
candidate versions found which didn't match: 1.1.0, 0.4.1, 0.4.0, ...
location searched: crates.io index
required by package `octocrab v0.8.1`
```

Looks like arc-swap 0.4.6 and 0.4.7 were yanked due to a soundness issue. Also looks like this project has already been updated to ^1.0.0 (which was also yanked, but 1.1.0 should be compatible?) and just needs to be re-released.

As a workaround I'm going to use a git dependency for now. Thanks!

**Comment by dbanty** [comment]
For reference it looks like this happened as a result of https://github.com/vorner/arc-swap/issues/45 just 30 minutes ago. Unlucky that I happened to try to install right after that.

**Comment by vorner** [comment]
Crap, I didn't expect this consequence of yanking all the broken versions. But in hindsight, it makes complete sense. There doesn't seem to be a good way out of a soundness bug :-|.

Anyway, sorry for the disruption, I've backported the fix to the 0.4 version, just released as 0.4.8. So it should work now, hopefully.

**Comment by dbanty** [comment]
Awesome, thanks @vorner! Confirmed it's all working by removing/re-adding octocrab's released version.

Since this isn't an immediate issue anymore I'll close this.

**Comment by XAMPPRocky** [comment]
I'm going to leave the issue open until I update the arc-swap dependency
