### ISSUE TITLE
Upgrade to hyper/http 1.0

### ISSUE THREAD

**Issue by jonhoo** [XAMPPRocky/octocrab#492]
Now that version 1.0 of the hyper and http* crates are out, octocrab should probably follow suit. Unfortunately, it's a decently heavy lift, especially due to `Body` changing from a concrete type to a trait (https://github.com/hyperium/hyper/issues/2345). I took a stab at it, but quickly got lost in a sea of `<B: Body>`s, and figured I'd leave it to those who know the library best.

A few bits I did pick up that may come in handy for someone wanting to take this on:

- `body::to_bytes(body).await?` becomes `body.collect().await?.to_bytes()` via [`http_body_util::BodyExt`](https://docs.rs/http-body-util/latest/http_body_util/trait.BodyExt.html)
- The old `Body` becomes `BoxBody<hyper::body::Bytes, hyper::Error>` via [`http_body_util::combinators::BoxBody`](https://docs.rs/http-body-util/latest/http_body_util/combinators/struct.BoxBody.html) _if_ you want to keep it fully type-erased like it is today.
- There is no more pooling http client, nor a `Connector` trait (or rather, they're relegated to [`hyper_util::client::legacy`](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/index.html)). Instead, there is now [`hyper::client::conn::http1::Connection`](https://docs.rs/hyper/latest/hyper/client/conn/http1/struct.Connection.html).

Also note that this will obviate:

- https://github.com/XAMPPRocky/octocrab/pull/491
- https://github.com/XAMPPRocky/octocrab/pull/489
- https://github.com/XAMPPRocky/octocrab/pull/488
- https://github.com/XAMPPRocky/octocrab/pull/487

which can probably all be closed in favor of this tracking issue.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! 

> > I took a stab at it, but quickly got lost in a sea of <B: Body>s

Yeah I tried upgrading other crates I maintain to 1.0.0 as a test, but this upgrade has been pretty painful in my experience, so I haven't made it a priority.

**Comment by jonhoo** [comment]
Also worth linking this, which it took me a bit to find: https://hyper.rs/guides/1/upgrading/

**Comment by CommanderStorm** [comment]
@jonhoo
FYI: I think this issue is closed as https://github.com/XAMPPRocky/octocrab/pull/564 has been merged and released in [`v0.34.0`](https://github.com/XAMPPRocky/octocrab/pull/565)

=> I think this issue can be closed ^^
