### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by johnrichardrinehart** [XAMPPRocky/octocrab#497]
How can I build an instance of an `Octocrab` client that uses timeouts? I've enabled the feature but all of the timeout values are [hard-coded to `None`](https://github.com/XAMPPRocky/octocrab/blob/551871a5766339f47119ee84686ce2dd4310e6ba/src/lib.rs#L749-L754) without `Builder` methods that allow for changing these values from `None`.

**Comment by CommanderStorm** [comment]
@johnrichardrinehart I think this issue can be closed given that #498 was merged ^^
