### ISSUE TITLE
Fields missing?

### ISSUE THREAD

**Issue by dmgorsky** [XAMPPRocky/octocrab#499]
Inspecting the code, noticed that
`pub struct ListCollaboratorsBuilder` might lack `affiliation`, `permission` 
and 
`pub struct Collaborator` might lack `role_name`
according to
https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#list-repository-collaborators

**Comment by shawnyu5** [comment]
I've also noticed with [octocrab::models::workflows::Run](https://docs.rs/octocrab/latest/octocrab/models/workflows/struct.Run.html) is missing top level keys, such as `run_started_at`. 

Not sure if this is by design, but it seems the structs defined in Octocrab is not a one-to-one mapping of what the GitHub api returns.

**Comment by shawnyu5** [comment]
There's this section in the docs that talks about how to extend octocrab types

 https://github.com/XAMPPRocky/octocrab?tab=readme-ov-file#:~:text=You%20can%20also%20easily%20access%20new%20properties%20that%20aren%27t%20available%20in%20the%20current%20models%20using%20serde.

**Comment by dmgorsky** [comment]
I guess I'll review actual schemas some day

**Comment by dmgorsky** [comment]
So I took `yaml` from here https://github.com/github/rest-api-description/tree/main/descriptions/api.github.com

Extracted URLS with tags
```rust
use std::{fs::File,
          io::BufWriter};
use std::io::Write;

use serde_yaml::Value;

fn main() -> std::io::Result<()> {
    fn find_methods(gk: Option<&Value>) -> Option<&Value> {
        let methods: Vec<_> = "get|post|put|patch|delete".split('|').collect();
        for method in methods {
            let try_method = gk.and_then(|gk| gk.get(method));
            if try_method.is_some() { return try_method; }
        }
        None
    }
    //
    
    let delim = '\t';
    let f = File::open("api.github.com.2022-11-28.yaml").unwrap();
    let out_file = File::create("api.github.com.2022-11-28.tsv").unwrap();
    let mut writer = BufWriter::new(out_file);
    
    let data: Value = serde_yaml::from_reader(f).unwrap();
    let q = data.get("paths").unwrap();
    writer.write_all(format!("TAG{delim}URL\n").as_ref())?;
    println!("TAG{delim}URL");
    match q {
        Value::Sequence(sq) => println!("Sequence of {}", sq.len()),
        Value::Mapping(m) => {
            for key in m.keys() {
                let gk = m.get(key);
                let gk = find_methods(gk);
                let gk = gk
                    .and_then(|gk| gk.get("tags"))
                    .and_then(|gs| gs.as_sequence());
                
                if let Some(gk_contents) = gk {
                    if let Some(tag) = gk_contents.first() {
                        print!("{}{delim}", tag.as_str().unwrap());
                        writer.write_all(format!("{}{delim}", tag.as_str().unwrap()).as_ref())?;
                    } else {
                        print!("-{delim}");
                        writer.write_all(b"-{delim}\n")?
                    }
                }
                println!("{}", key.as_str().unwrap());
                writer.write_all(format!("{}\n", key.as_str().unwrap()).as_ref())?
            }
        }
        Value::String(st) => println!("String {}", st),
        _ => println!("---")
    }
    let _ = writer.flush();
    
    Ok(())
}

```
and here is the result.
[api.github.com.2022-11-28.tsv.zip](https://github.com/XAMPPRocky/octocrab/files/13866726/api.github.com.2022-11-28.tsv.zip)
Now going to sort it and roughly compare with the crate.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! PRs adding missing fields are welcome and encouraged 🙂

**Comment by dmgorsky** [comment]
> Thank you for your issue! PRs adding missing fields are welcome and encouraged 🙂

we might use https://github.com/dmgorsky/github_api_check_for_octocrab for that
