### ISSUE TITLE
`.teams().repos().remove()` always fails with EOF error

### ISSUE THREAD

**Issue by manchicken** [XAMPPRocky/octocrab#504]
There are several APIs which result in the GitHub API which return `204` and have no response body. [`DELETE /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}`](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#remove-a-repository-from-a-team) is one of those.

At the moment, the `FromResponse::from_response()` function does not support responses with no body. It looks like this:

```rust
/// A trait for mapping from a `http::Response` to an another type.
#[async_trait::async_trait]
pub trait FromResponse: Sized {
    async fn from_response(response: http::Response<hyper::Body>) -> crate::Result<Self>;
}

#[async_trait::async_trait]
impl<T: serde::de::DeserializeOwned> FromResponse for T {
    async fn from_response(response: http::Response<hyper::Body>) -> crate::Result<Self> {
        let (_, body) = response.into_parts();
        let body = hyper::body::to_bytes(body)
            .await
            .context(crate::error::HyperSnafu)?;
        let de = &mut serde_json::Deserializer::from_slice(&body);

        // THIS COMMENT ADDED FOR DEMONSTRATION PURPOSES, IGNORE UNTIL LATER

        return serde_path_to_error::deserialize(de).context(crate::error::JsonSnafu);
    }
}
```

I have added a test in [this draft PR](https://github.com/XAMPPRocky/octocrab/pull/503/files#diff-e6a85e87a9357bc949cf0f3f041694d2df2a5f5cb79b7d20df260cbf3e96b78e) which demonstrates the error.

I think the fix is in that self-same `FromResponse::from_response()` function, right where I added the comment. It seems like you could just check whether `body.is_empty()` and then return something that conforms to the `crate::Result<Self>`.

I've been trying to put together a fix for it, but my Rust is perhaps too weak and I am having a difficult time figuring out exactly what I can return from this function to make it play nice.

If anybody has any thoughts, I'm happy to do the work on a fix here. I already have a test, and I'm going to expand the test once I navigate this issue.

Collaboration is appreciated, thanks.

Solidarity.

**Comment by manchicken** [comment]
I could also see changing the `Octocrab::delete()` function, as I don't think any of the `DELETE` APIs return a body in the response.

**Comment by manchicken** [comment]
So, I just pushed commits to my PR #503. Those changes do kinda fix this issue, but I don't like the fix since it relies on using what seems to conventionally be a non-public function.

I'm trying to keep the change as light-touch as possible so that it won't break anybody's code. I'm still pretty new to the language, though, so I'm probably missing something. I would appreciate feedback.

**Comment by manchicken** [comment]
It looks like `.teams().repos().add_or_update()` may also be failing with errors, but the code in the current version of the crate suppresses the error.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I think you just need to use the `_delete` method instead of `delete`.

**Comment by manchicken** [comment]
Are there any delete methods for which `.delete()` functions as expected? I wasn't able to find any.

**Comment by XAMPPRocky** [comment]
I don't think so, but I don't have an complete reference of GitHub APIs in my head 😄

**Comment by manchicken** [comment]
~ Mike StemleOn Jan 8, 2024, at 07:04, XAMPPRocky ***@***.***> wrote:﻿
I don't think so, but I don't have an complete reference of GitHub APIs in my head 😄

**Comment by manchicken** [comment]
Here's the CSV file: https://github.com/XAMPPRocky/octocrab/discussions/506

**Comment by XAMPPRocky** [comment]
I think we can just make `delete` equivalent to `_delete`. That seems like the solution to me.

**Comment by manchicken** [comment]
Groovy. I’ll add some tests and see how that goes. This seems like a breaking change, somehow?~ Mike StemleOn Jan 8, 2024, at 07:57, XAMPPRocky ***@***.***> wrote:﻿
I think we can just make delete equivalent to _delete. That seems like the solution to me.

**Comment by XAMPPRocky** [comment]
> Groovy. I’ll add some tests and see how that goes. This seems like a breaking change, somehow?

Yes but that's fine.

**Comment by manchicken** [comment]
Groovy. I'll go in that direction. I should have an updated PR in a week or two.
