### ISSUE TITLE
Query releases

### ISSUE THREAD

**Issue by simonsan** [XAMPPRocky/octocrab#51]
Would it make sense to add a `releases` endpoint to easily query for releases of a repository and loop through them with an iterator?

Would love that, as that would make updating software from github releases much easier.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! There is actually already a `releases` endpoint, I just haven't released it. I plan to try to publish a new version this week. https://github.com/XAMPPRocky/octocrab/blob/master/src/api/repos/releases.rs

**Comment by simonsan** [comment]
> 
> 
> Thank you for your issue! There is actually already a `releases` endpoint, I just haven't released it. I plan to try to publish a new version this week. https://github.com/XAMPPRocky/octocrab/blob/master/src/api/repos/releases.rs

Oh thanks for answering so fast, I just read shortly through the readme and didn't find it. My bad, should have probably checked it in the code/docs.rs myself. ;-)

**Comment by XAMPPRocky** [comment]
Apparently I had already released this in 0.8.0, however I've now added documentation links in 0.8.2.
