### ISSUE TITLE
`actions -> download_artifact` fails with an auth issue

### ISSUE THREAD

**Issue by flenter** [XAMPPRocky/octocrab#563]
Downloading artifacts for actions no longer seems to work. This seems to be caused by the azure blob storage now preferring the authorization header information over the values provided by the query parameters.

Here's a blog post describing the issue for a golang library:
https://medium.com/@DiggerHQ/chasing-a-nasty-bug-a-tale-of-excessive-auth-40d8bf5cf192

It would be good perhaps for the `execute` function to not always add authorization headers to all requests (but maybe only to the ones that go to the `base_uri`). Adding it to all requests that go through `pub async fn execute` function regardless of the targetted URL might cause the library to leak credentials to other servers besides github. 

I am not familiar enough with the API to know whether changing this behaviour is a good idea (nor am I really experienced with writing Rust code, which is why I haven't created a PR).

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I believe this has already been fixed by #562

**Comment by flenter** [comment]
Awesome! Love it
