### ISSUE TITLE
Cannot directly pass SecretString for token auth

### ISSUE THREAD

**Issue by flying-sheep** [XAMPPRocky/octocrab#594]
Given I have

```rust
let github_token: secrecy::SecretString = ...;
```

I can either do

```rust
octocrab::Octocrab::builder()
	.personal_token(github_token.expose_secret().to_owned())
	.build()?,
```

or, if I knew how to do that,

```rust
octocrab::OctocrabBuilder::new_empty()
	.with_auth(octocrab::auth::Auth::PersonalToken(github_token))
	.with_service(???)
	.with_layer(???)
	.build()?,
```

It seems weird to me that `OctocrabBuilder<..., DefaultOctocrabBuilderConfig, NoAuth, ...>::personal_token(...)` returns `Self` and not `OctocrabBuilder<..., Auth, ...>`.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! That does seems like an oversight, I'd be happy to review a a PR that makes this possible.

**Comment by flying-sheep** [comment]
Done! I still wonder about the way `OctocrabBuilder`’s type parameters work, but that’s not relevant for this PR.
