### ISSUE TITLE
Should `RateLimit::reset` be a `u64`?

### ISSUE THREAD

**Issue by smoelius** [XAMPPRocky/octocrab#614]
Re this line: https://github.com/XAMPPRocky/octocrab/blob/131ddc02b2546f8c9863f98703fb92a3945ed8e8/src/models.rs#L959

The [GitHub REST API docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) describe the corresponding header (`x-ratelimit-reset`) as "UTC epoch seconds".

This suggests that users should pass the value to [`Duration::from_secs`](https://doc.rust-lang.org/std/time/struct.Duration.html#method.from_secs).

Since `Duration::from_secs` expects a `u64`, should this field be a `u64`?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yeah I think that's a reasonable change.
