### ISSUE TITLE
Return result instead of panic when returning an `installation` Octocrab instance

### ISSUE THREAD

**Issue by krishmas** [XAMPPRocky/octocrab#641]
https://github.com/XAMPPRocky/octocrab/blob/7e280be901c378a1e162c37f909ea6590c6ff4ba/src/lib.rs#L981

Would be nicer to return an Error result (like other functions that return different types of Octocrabs do) instead of panicking so the application using doesn't immediately crash out

**Comment by XAMPPRocky** [comment]
Thank you for your issue! A PR adding this would be welcome 🙂
