### ISSUE TITLE
Page fields are not filled for different handlers like Issues, PRs, ...

### ISSUE THREAD

**Issue by MalteHerrmann** [XAMPPRocky/octocrab#659]
### Problem

The returned `Page<...>` instances from e.g. the `ReleasesHandler` or `PullRequestHandler` have pretty much all of their fields set to `None` values, even though the objects like releases or pull requests could be successfully retrieved. Since there were `items` returned, I would expect the `next`, and `first` fields to work as well as the `totalCount`.

![image](https://github.com/XAMPPRocky/octocrab/assets/42640438/a76646a9-695d-4a37-9e64-68e8af2004de)

### How To Reproduce

The following test showcases this.

```rust
    #[tokio::test]
    async fn test_get_release() {
        let oc = octocrab::instance();
        let repos = oc.repos("evmos", "evmos");
        let rls_list = repos.releases().list().send().await.unwrap();
        assert!(rls_list.items.len() > 0);          // <--- this is passing
        assert!(rls_list.total_count.unwrap() > 0)  // <--- total count has a None value returned
    }
```

**Comment by M0dEx** [comment]
I am having the same problem with the `RepoHandler`.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I don't currently have time to investigate a fix myself but I'm happy to review a PR addressing the issue. 🙂

**Comment by MalteHerrmann** [comment]
I was looking into a potential "fix" and realised that I was just misunderstanding the purpose of these fields.
It works just fine according to the behavior of the GitHub API - for reference if anyone else is confused by this:

- `total_count` is not reported by the GitHub API for these kinds of requests
- if all entries have been returned, the next, prev, last, and first entries will be empty

These were the assumptions I did not know of - in other cases the fields are filled as expected.
