### ISSUE TITLE
Consider removing doc-cfg crate

### ISSUE THREAD

**Issue by Jake-Shadle** [XAMPPRocky/octocrab#66]
As far as I can see the doc-cfg crate is being used in exactly 1 place, but it's a crate that has seen 0 activity in almost 2 years and pulls in multiple severely outdated crates that are duplicated with more recent versions that are brought in by other dependencies (eg proc-macro2 etc)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I was unaware it is apparently available in rustdoc itself for doctors. So I've removed it now and replaced it with.

```rust
#[cfg_attr(docsrs, doc(cfg(feature = "stream")))]
```
