### ISSUE TITLE
Make the Fields in models::timelines::Source Public

### ISSUE THREAD

**Issue by matilda-ray-kerria** [XAMPPRocky/octocrab#705]
I am currently developing a program to manage GitHub issues and pull requests using the octocrab crate. While trying to extract information about related pull requests from the issue timeline, I noticed that the fields in `models::timelines::Source` are private.

```rust
use octocrab::{
    models::{timelines::Source, Event},
    Octocrab,
};

#[tokio::main]
async fn main() -> octocrab::Result<()> {
    let octocrab = Octocrab::builder()
        .personal_token("GITHUB_PERSONAL_TOKEN".to_string())
        .build()?;

    let page = octocrab
        .issues(OWNER, REPO)
        .list_timeline_events(1u64)
        .per_page(100)
        .send()
        .await?;

    for event in &page {
        if Event::CrossReferenced == event.event {
            if let Some(Source { issue, .. }) = &event.source {
                if issue.pull_request.is_some() {
                    println!(
                        "Found related pull request: #{} - {}",
                        issue.number, issue.title
                    );
                }
            }
        }
    }

    Ok(())
}
```

```
error[E0451]: field `issue` of struct `Source` is private
  --> src/main.rs:24:34
   |
24 |             if let Some(Source { issue, .. }) = &event.source {
   |                                  ^^^^^ private field

For more information about this error, try `rustc --explain E0451`.
error: could not compile `octocrab_example` (bin "octocrab_example") due to 1 previous error
```

https://github.com/XAMPPRocky/octocrab/blob/9fbf59c42a4c267204980955a1c70b80ee919964/src/models/timelines.rs#L97-L102

Since `Source` does not have getter methods defined for its fields, I cannot access these values. Would it be possible to change these fields to public? Alternatively, is there another method to achieve this?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Seems like an oversight, if you'd like to make a PR making them public I can review it.

**Comment by matilda-ray-kerria** [comment]
I'm sorry for forgetting to include the 'closes' keyword in my pull request.
