### ISSUE TITLE
`IssueHandler::add_assignees` passes some kind of ID where Github docs say strings

### ISSUE THREAD

**Issue by rocallahan** [XAMPPRocky/octocrab#86]
https://docs.github.com/en/rest/reference/issues#add-assignees-to-an-issue

> assignees | array of strings | body | Usernames of people to assign this issue to

```    pub async fn add_assignees(
        &self,
        number: u64,
        assignees: &[u64],
    ) -> Result<models::issues::Issue> {
```

I don't know who's right but I hope the Github docs are right...

**Comment by chazkiker2** [comment]
`number` refers to the `issue_number`, which is specified as type `integer` for the GitHub docsx

#### description of `issue_number` param from docs:

issue_number | integer | path | issue_number parameter
-- | -- | -- | --


#### use of `number` argument in Octocrab:

https://github.com/XAMPPRocky/octocrab/blob/bb3f7bee6948f0986b37cbac3405710f128c6489/src/api/issues.rs#L221

so Octocrab and Docs are both right :)
