### ISSUE TITLE
Support for commit logs and messages?

### ISSUE THREAD

**Issue by StephanSchmidt** [XAMPPRocky/octocrab#89]
(Hi, I've looked around for a support channel or any way to ask questions but didn't find any)

From the documentation I can't find a way to read commit logs for a branch/repo, is there any?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've created a GitHub Discussions board if you want to ask questions.

I don't think there is support for that currently (beyond using the HTTP API directly), however adding it should be easy, and I would accept a PR that adds that functionality.

**Comment by StephanSchmidt** [comment]
Thanks, sorry again for posting here, I'll check discussions, and use the HTTP API.
