### ISSUE TITLE
Octocrab and sqlx

### ISSUE THREAD

**Issue by StephanSchmidt** [XAMPPRocky/octocrab#91]
I want to use sqlx, octocrab and sqlxmq in a project.

Octocrab seems to have a tokio 0.2 dependency, and sqlx a tokio 1.x dependency. So I need to run sqlx with async std not tokio. But sqlxmq has a dependency on sqlx-tokio 1.x and sqlx can't run in two modes, so I would need to run the project sqlx also on tokio which then does not work with octocrab.

Is my assumption even right that Octocrab works with tokio 0.2?

Is there a way for Octocrab to work with async-std? Or with Tokio 1.x?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Are you sure you're using an up to date version of Octocrab? We don't depend on Tokio directly but depend on it through `reqwest` 0.11, and that depends on Tokio 1.0

**Comment by StephanSchmidt** [comment]
Thank you, I will take a look, sorry for being mistaken. Thanks for the very fast answer.

**Comment by XAMPPRocky** [comment]
Closing as it seems like its fixed.
