### ISSUE TITLE
feat: Test API — allow for easier unit tests in client code via feeding `octocrab::Octocrab` synthetic data

### ISSUE THREAD

**Issue by chazkiker2** [XAMPPRocky/octocrab#93]
# Description

This is a feature request, feel free to close this issue immediately if you hate it. 

But it would be very convenient to be able to feed synthetic data to `octocrab::Octocrab` so client code could easily write unit tests with consistent data (instead of manually making a github organization/repo, etc.)

You could call this test struct `Moctocrab` :wink:

# Example Use Case

Say I had the following function (as I do in fact have :laughing: ) that counted the number of PRs created in the last 30 days for the specified repository in the specified organization.\
It would be nice to be able to write a unit test that passes in my customized/mocked `octocrab::Octocrab` instance with pre-determined data so as to verify that this function works consistently and as expected.

```rust
use chrono::{Duration, Utc};
use fehler::throws;

#[throws]
async fn count_pull_requests(octo: &octocrab::Octocrab, org_name: &str, repo_name: &str) -> usize {
    let mut page = octo
        .pulls(org_name, repo_name)
        .list()
        // take all PRs -- open or closed
        .state(octocrab::params::State::All)
        // sort by date created
        .sort(octocrab::params::pulls::Sort::Created)
        // start with most recent
        .direction(octocrab::params::Direction::Descending)
        .per_page(255)
        .send()
        .await?;

    let thirty_days_ago = Utc::now() - Duration::days(30);
    let mut pr_count: usize = 0;

    loop {
        let in_last_thirty_days = page
            .items
            .iter()
            // take while PRs have been created within the past thirty days
            .take_while(|pr| pr.created_at > thirty_days_ago)
            .count();

        pr_count += in_last_thirty_days;
        if in_last_thirty_days < page.items.len() {
            // No need to visit the next page.
            break;
        }

        if let Some(p) = octo.get_page(&page.next).await? {
            page = p;
        } else {
            break;
        }
    }

    pr_count
}
```

**Comment by chazkiker2** [comment]
i see now that you have a test file which shows a reasonable enough way to do this!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'm definitely open to improving the testability of octocrab. However to provide a mock version of Octocrab, it'd probably require some kind of code-generation from GitHub's OpenAPI, otherwise it wouldn't be maintainable. Which may be something that happens in the future. We are using `wiremock` to fake responses for tests in the repo currently if you want something that works today.

**Comment by chazkiker2** [comment]
that makes plenty of sense. 

Happy to follow suit with `wiremock`! Thanks for the response :)
